default_stages:
  - commit

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
      
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
